### PR TITLE
updating some stuff

### PR DESCRIPTION
**Pull request by TheMoksej**
1. `get_website_health()` and `get_website_stats()` were raising 404's because of uneccessary `/`
2. time is now shown in seconds instead of ms
3. better errors
4. bumping the version to `1.0.0` because me and Cairo have decided to do so.

### CODE REVIEW

**Comment by advaith1** [comment]
> time is now shown in seconds instead of ms

why?

**Comment by TheMoksej** [comment]
> > time is now shown in seconds instead of ms
> 
> why?

seconds are easier to read

**Comment by imvaskel** [comment]
I would use milliseconds, not seconds.

**Comment by advaith1** [comment]
milliseconds are pretty standard

**Review by carolinaisslaying — APPROVED** [review]

**Pull request merged**
