### PR TITLE
1.1.0

### PR DESCRIPTION
**Pull request by TheMoksej**
Hello good sir Cairo, you can test this

### CODE REVIEW

**Comment by TheMoksej** [comment]
Look I fixed the conflicts!!

**Comment by TheMoksej** [comment]
Found some stuff that I'll be trying to fix. (will finish later today cause too busy rn)

**Comment by TheMoksej** [comment]
TODO: Fix stupid mistakes

**Comment by TheMoksej** [comment]
Forgot to undraft this a while ago, been using this since October, everything works without any issues.

**Review by carolinaisslaying — APPROVED** [review]

**Pull request merged**
